### ISSUE TITLE
card in cards returning null for some reason.

### ISSUE THREAD

**Issue by Arima57** [ShadowBlip/OpenGamepadUI#280]
I don't exactly know what to make of it, but it's exactly as the title says. The program was not running for me so I wanted to take a look.

![image](https://github.com/ShadowBlip/OpenGamepadUI/assets/139682255/e3a86ce3-cdbf-4a6f-bd08-d16522ffe4f9)

What I can tell is that it likely has something to do with Nvidia optimus. I know nvidia is not supported, but the accompanying intel card should be innocent. As it turns out running program in Nvidia only mode lets it run somehow and not the other way around.

Adding an extra security check and saying 'if card != null' fixes the issue, for now, but that's not very indicative of the issue.... I guess.

**Comment by ShadowApex** [comment]
Thank you for reporting this! This appears to be because we are not checking if the GPU card is null before adding it to the list of GPUs.

Could you also look in `~/.local/share/opengamepadui/logs` and see if there are any warnings like "Device vendor string not recognized". I'm curious if your Intel card is reporting a vendor string we're not accounting for.

Thanks!

**Comment by Arima57** [comment]
Hmmm, so I tried messing around and figured out the card that is not being recognised is the Nvidia one, (the intel one is recognized as plain 'Intel'). But the nvidia one is simply getting detected before the intel one which puts a null value at the beginning of the array. Additionally, the nvidia string is 'NVIDIA Corporation', though that doesnt make much of a difference at all. That should be all.
