### ISSUE TITLE
Help needed for Gentoo Ebuild

### ISSUE THREAD

**Issue by bell07** [ShadowBlip/OpenGamepadUI#336]
I am working on Gentoo Ebuild for OpenGamepadUI.

Gentoo is source based Linux distribution. The Ebuild is the build instruction for the package manager.

Basically I can use `make build` inside the ebuild, but currently this fails because of sandbox restriction of package manager.
 The package manager (portage) does not allow additional downloads during build process. (The flow is download -> unpack -> configure -> build -> install into temp folder -> Merge (copy) into /)

`make build` try to download the `Godot_v4.2.2-stable_export_templates.tpz` that fails.

I am not experienced in godot and Makefile development, so I do not know how to solve the issue byself.

1) Is the template really needed for system release that is compiled on target device?

2) If needed, is there a way to just use system-installed `/usr/share/godot/export_templates/4.2.2/linux_debug.x86_64` or `/usr/share/godot/export_templates/4.2.2/linux_release.x86_64`
(Then I write additional godot-templates ebuild that installs the right templates matching godot version)

**Comment by ShadowApex** [comment]
Yes, the export template is required in order to build a release. The template is the core engine and is used to bundle the engine with the assets, scripts, and libraries for the final binary. You can also compile the templates themselves from the Godot Engine source, if required.

We could modify the `Makefile` to optionally look for a variable of where to look for the templates if you want to use a system-installed version of the template.

**Comment by ShadowApex** [comment]
You can now use the `EXPORT_TEMPLATE` variable to set the full path to the system-installed export template when doing `make build`.
