### ISSUE TITLE
Simplify building addons from source

### ISSUE THREAD

**Issue by Riteo** [ShadowBlip/OpenGamepadUI#382]
Hi, currently the addons are just some binary blobs. I'm aware that this was a deliberate choice to increase build speed (#90) and all of the addons are indeed free software under the GPL but I'm having some issues with them.

You see, outside of ideological stuff, I can't run the blobs directly as I have a different software setup (musl libc) and I'd really appreciate being able to rebuild/patch the addons without doing it manually for each one.

I can take a stab at making a PR if that's ok. It shouldn't take long: I'm thinking about putting the source code of each addon as a sumbodule and adding a makefile entry to each shared object.

**Comment by ShadowApex** [comment]
Completely understandable. I would also love to see adding the addons back as source submodules. I think the main things to consider in order for us to do this are:

1. Local & CI build times
2. GLIBC/MUSL version in CI

Local build times are important, but a proper Makefile should be able to ensure addons don't need to be rebuilt unless changes are made. So this should be do-able.

For the version of libc, right now our CI system is configured with [Semantic Release](https://github.com/semantic-release/semantic-release) to automatically build and publish a new release of OpenGamepadUI when changes are merged into the `main` branch. We will need to ensure that with these changes our CI system can build those addons with a specific GLIBC version (and maybe a MUSL version?). This is required so that we can build and publish a version of OpenGamepadUI that is also compatible with SteamOS, which uses an older version of GLIBC than our build container.

**Comment by ShadowApex** [comment]
No problem! Thank you for bringing up this issue!
