### ISSUE TITLE
SDL2 Support

### ISSUE THREAD

**Issue by Gamecubert** [ShadowBlip/OpenGamepadUI#67]
It would be nice to have the ability to use SDL2 mappings for unusual gamepads. Via plugin or a direct implementation. [Here](https://github.com/gabomdq/SDL_GameControllerDB) is what I'm referring to btw. Not to be confused with another project with a similar name.

**Comment by Gamecubert** [comment]
Just so people know I can't code but this idea didn't seem to outlandish so I thought it would be good to at least get it out there.

**Comment by ShadowApex** [comment]
The Godot engine already supports SDL2 mappings, so this shouldn't be difficult if not already supported:
https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-add-joy-mapping

Was there a specific mapping you were looking to support?

**Comment by Gamecubert** [comment]
Nope, my apologize I didn't notice that. Thank you for notifying me. This project shows lots of promise.

**Comment by Pinephoneman** [comment]
I got an idea and maybe this could be tagged on. Why not have a startup function that can map any device (gamepad or not) to xinput compatible controls then use that when opening games. The mapping could be fine tuned on a per game basis. As of right now i have issues with steam deck mapping wrong inputs of trying to use pc controls instead of xinpute based ones. Esentialy any device could map any button or combination of buttons to specific xinput functions. You could even have device profiles for bluetooth devices and save mappings per device.

**Comment by Pinephoneman** [comment]
The only reason i suggest this is because support for each and every input method is an uphill battle but setting up a system like this would allow any device to be set up in just a few seconds. It could be like how retroarch goes button by button in one go to get every input implamented quickly. You could also go the steam input route and have a backup keyboard map layout and map each button to a keyboard press and finetune that for the games that need it. I would suggest having both due to some games having more granular movement using xinput joycons as apposed to wasd key being all or nothing.

**Comment by pastaq** [comment]
We're working on a more comprehensive tool that will work in concert with OpenGamepadUI to overcome some limitations we've found with the polling rate, managing additional "keyboard" devices on some handhelds, and balancing device management between multiple programs. This will essentially do what you are suggesting, but in a standard way that can be expanded by other 3rd party applications. TBS the original issue is already accounted for so I'm going to close this it for now.

**Comment by Pinephoneman** [comment]
Sounds good
